# Site settings
title: Turning the Other Cheek
email: whahn09@gmail.com
description: Wayne's story about fighting colorectal cancer.
url: "http://waynehahn.github.io"
twitter_username: whahn09
facebook_username:  wayne.hahn.5
paginate: 3
avatar: http://1.gravatar.com/avatar/e16dd74f3207b51f5fc5217934968fd1
disqus: waynehahn
footer-links:
  email: whahn09@gmail.com
  facebook: wayne.hahn.5
  twitter: whahn09
  rss: waynesfeed

# Build settings
markdown: kramdown
permalink: /:title

#Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Frani hahn
      layout: "post"
      comments: true
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"
