# Site settings
title: Turning the Other Cheek
description: Wayne's story about fighting colorectal cancer.
url: "http://waynehahn.github.io"
email: whahn09@gmail.com
twitter_username: whahn09
facebook_username:  wayne.hahn.5
paginate: 4
avatar: http://1.gravatar.com/avatar/e16dd74f3207b51f5fc5217934968fd1
disqus: waynehahn
footer-links:
  email: whahn09@gmail.com
  facebook: wayne.hahn.5
  twitter: whahn09
  rss: waynesfeed

# Build settings
markdown: kramdown
permalink: /:title

# Contact Section

social:
  icon: 'facebook', link: 'http://facebook.com/wayne.hahn5'

#Default settings
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author: Frani Hahn
      layout: "post"
      comments: true
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "page"
